DROP SEQUENCE SEC_USUARIOS_OID;
DROP TABLE USUARIOS;
CREATE TABLE USUARIOS (
	NIF VARCHAR2(10) NOT NULL UNIQUE,
	NOMBRE VARCHAR2(25) NOT NULL,
	APELLIDOS VARCHAR2(75),
	EMAIL VARCHAR2(75) NOT NULL UNIQUE,
	PASS VARCHAR2(75) NOT NULL,
	FECHA_NACIMIENTO DATE,
	OID_USUARIO INTEGER NOT NULL,
	PRIMARY KEY (OID_USUARIO) );
    
CREATE SEQUENCE SEC_USUARIOS_OID
START WITH 1 INCREMENT BY 1 NOMAXVALUE;

CREATE OR REPLACE TRIGGER INSERTAR_USUARIO_OID
BEFORE INSERT ON USUARIOS
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  SELECT SEC_USUARIOS_OID.NEXTVAL INTO :NEW.OID_USUARIO FROM DUAL;
END;
/

CREATE OR REPLACE PROCEDURE INSERTAR_USUARIO 
  (P_NIF IN USUARIOS.NIF%TYPE,
   P_NOM IN USUARIOS.NOMBRE%TYPE,
   P_APE IN USUARIOS.APELLIDOS%TYPE,
   P_FECHA_NAC IN USUARIOS.FECHA_NACIMIENTO%TYPE,
   P_EMAIL IN USUARIOS.EMAIL%TYPE,
   P_PASS IN USUARIOS.PASS%TYPE
   ) IS
BEGIN
  INSERT INTO USUARIOS(NIF, NOMBRE,APELLIDOS, FECHA_NACIMIENTO, EMAIL, PASS)
  VALUES (P_NIF,P_NOM,P_APE, P_FECHA_NAC, P_EMAIL, P_PASS);
END;
/


CREATE OR REPLACE PROCEDURE MODIFICAR_USUARIO 
(OID_USU_A_MOD IN USUARIOS.OID_USUARIO%TYPE,
 NOM_USU_A_MOD IN USUARIOS.NOMBRE%TYPE,
 APE_USU_A_MOD IN USUARIOS.APELLIDOS%TYPE) IS
BEGIN
  UPDATE USUARIOS
  SET NOMBRE=NOM_USU_A_MOD, APELLIDOS=APE_USU_A_MOD
  WHERE OID_USUARIO = OID_USU_A_MOD;
END;