DECLARE

OID_JUAN INTEGER;
OID_JOSE INTEGER;
OID_MATILDE INTEGER;
OID_LUISA INTEGER;

BEGIN


INSERTAR_USUARIO('11111111A','Juan','Pérez Martín', '1/1/1980', 'juan@us.es', 'qwerty' );
OID_JUAN := SEC_USUARIOS_OID.CURRVAL;
INSERTAR_USUARIO('11111112B','Josefa','López Consuegra', '1/1/1980', 'josefa@us.es', '123456' );
OID_JOSE := SEC_USUARIOS_OID.CURRVAL;
INSERTAR_USUARIO('11111113C','Matilde','Arjona Gómez', '1/1/1980', 'matilde@us.es', 'matilde' );
OID_MATILDE := SEC_USUARIOS_OID.CURRVAL;
INSERTAR_USUARIO('11111114D','Luisa','García Marín','1/1/1980', 'luisa@us.es', 'qwerty' );
OID_LUISA := SEC_USUARIOS_OID.CURRVAL;
COMMIT;

END;

